name: date_input_form_field
description: "DateInputFormField is a Flutter widget that wraps a FormField and allows the user to enter a date in a simple, intuitive way."
version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

topics:
  - date input form field
  - date input text field
  - date picker
  - form field
  - text field