name: date_input_form_field
description: "DateInputFormField is a Flutter widget that wraps a FormField and allows the user to enter a date in a simple, intuitive way."
version: 1.0.0
homepage: https://github.com/ravikovind/date_input_form_field
repository: https://github.com/ravikovind/date_input_form_field
issue_tracker: https://github.com/ravikovind/date_input_form_field/issues

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

topics:
  - date-input
  - date-form-field
  - date-picker
  - date-text-field
  - form-field